export const servicesData = [
  {
    id: 1,
    image: "/assets/events/wedding-management.png",
    text: "Wedding planning & management",
    slug: "wedding-planning-management",
    duration: "1000ms",
    title: "Wedding planning & management",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to our world of unforgettable weddings at VR Event & Entertainment. We specialize in crafting your dream day into a flawless reality, offering meticulous planning and seamless management. With a passionate team dedicated to every detail, from elegant venues to exquisite decor and personalized touches, we ensure your wedding day surpasses all expectations. Trust us to transform your dreams into cherished memories that will last a lifetime.  Let us transform your vision into a cherished celebration that will be remembered for a lifetime. Discover the art of exceptional wedding planning with VR Event & Entertainment.
    `,
    additionalImages: [
      "/assets/events/wedding-services.png",
      "/assets/events/haldi.png",
      "/assets/events/mendi.png",
      "/assets/events/coctail.png",
      "/assets/events/dj-sound.png",
      "/assets/events/catering-buffet.jpg",
      "/assets/events/wedding-services.png",
      "/assets/events/entertainment.png",
      "/assets/events/hospitality.png",
    ],
    additionalServices: [
      "Wedding Ceremony",
      "Haldi Ceremony",
      "Mehndi",
      "Cocktail ceremony",
      "Dj light and sound",
      "Catering",
      "All type artist management",
      "Entertainment",
      "Hospitality",
    ],
  },
  {
    id: 2,
    image: "/assets/events/corporate-events.png",
    text: "Corporate events",
    slug: "corporate-events",
    duration: "1200ms",
    title: "Corporate Events",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to  VR Event & Entertainment, where corporate events meet unparalleled sophistication and seamless execution. Whether you're planning a prestigious conference, a dynamic product launch, or a memorable team-building retreat, our expert team is committed to delivering excellence at every stage. From innovative venue selection to bespoke thematic design and flawless logistical coordination, we ensure your event reflects your brand's unique identity and exceeds all expectations. Let us elevate your corporate gatherings to new heights of success and distinction. Partner with us for an unforgettable event that leaves a lasting impression.
    `,
    // additionalImages: [
    //   "/assets/images/service-single/2.jpg",
    //   "/assets/images/service-single/3.jpg",
    //   "/assets/images/service-single/2.jpg",
    //   "/assets/images/service-single/3.jpg",
    //   "/assets/images/service-single/2.jpg",
    //   "/assets/images/service-single/3.jpg",
    // ],
    // additionalServices: [
    //   "Wedding Ceremony",
    //   "Haldi Ceremony",
    //   "Mehndi",
    //   "Cocktail ceremony",
    //   "Dj light and sound",
    //   "Catering",
    //   "All type artist management",
    //   "Entertainment",
    //   "Hospitality",
    // ],
  },
  {
    id: 3,
    image: "/assets/events/artist-management.png",
    text: "Artist management",
    slug: "artist-management",
    duration: "1400ms",
    title: "Artist management",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, your premier destination for artist management and talent curation. With a passion for creativity and a dedication to excellence, we specialize in connecting you with the perfect performers to elevate your event to extraordinary heights. Whether you're planning a concert, festival, or private function, our extensive network of artists spans genres and styles, ensuring we match your vision with unparalleled talent. From negotiating contracts to coordinating logistics, we handle every detail with precision and professionalism, allowing you to focus on enjoying a flawless, unforgettable experience. Discover the art of exceptional entertainment management with us..
    `,
    additionalImages: [
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-fourteen.png",
      "/assets/events/artist/artsit-eight.png",
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
      "/assets/events/artist/artsit-four.png",
    ],
    additionalServices: [
      "Bollywood dance group",
      "Bhangra dance group",
      "Western dance group",
      "Folk dance group",
      "Rock band",
      "Sufi band",
      "Solo singer",
      "Duet singer",
      "Male female anchor",
      "DJ jockey",
      "Poetry artist",
      "Stand up comedian",
      "Magician",
      "Game coordinator",
      "Character artist",
      "Service boys and girls",
      "Volunteers",
      "International artist",
    ],
  },
  {
    id: 4,
    image: "/assets/events/themebased-decoration.jpg",
    text: "Theme Based Decoration",
    slug: "theme-based-decoration",
    duration: "1600ms",
    title: "Theme Based Decoration",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, where creativity meets craftsmanship in theme-based decorations that transform your event into a captivating experience. From whimsical fairy tales to sophisticated galas, we specialize in crafting bespoke themes that reflect your unique style and vision. Our dedicated team of designers and decorators meticulously curates every detail, from stunning props to enchanting lighting, ensuring each element harmonizes seamlessly to create an unforgettable ambiance. Whether it's a wedding, corporate event, or private party, let us turn your imagination into reality with our expert theme-based decorations. Elevate your event with us, where every theme comes to life with elegance and flair.
    `,
    additionalImages: [
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
    ],
    additionalServices: [
      "Wedding Ceremony",
      "Haldi Ceremony",
      "Mehndi",
      "Cocktail ceremony",
      "Dj light and sound",
      "Catering",
      "All type artist management",
      "Entertainment",
      "Hospitality",
    ],
  },
  {
    id: 5,
    image: "/assets/events/birtthday2.png",
    text: "Professional birthday planner",
    slug: "professional-birthday-planner",
    duration: "1000ms",
    title: "Professional birthday planner",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, your trusted partner in creating memorable birthdays that exceed expectations. Whether it's a milestone celebration or an intimate gathering, our professional birthday planners specialize in personalized experiences tailored to your preferences. From themed decor to entertainment and delectable cuisine, we handle every aspect with meticulous attention to detail, ensuring a stress-free and joyful celebration for you and your guests. Let us bring your birthday dreams to life with creativity, expertise, and a touch of magic. Celebrate in style with us, where every birthday becomes a cherished moment.
    `,
    additionalImages: [
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-fourteen.png",
      "/assets/events/artist/artsit-eight.png",
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
    ],
    additionalServices: [
      "Game",
      "Magic",
      "Puppet show",
      "Tattoo",
      "Name plate",
      "Stone name making",
      "Art and craft",
      "Key chain",
      "Balloon shooting",
      "Candle making",
      "Glow jar",
      "Candy",
      "Popcorn",
      "Archery",
      "Nail art",
      "Hair beading",
    ],
  },
  {
    id: 6,
    image: "/assets/events/school.jpg",
    text: "School & College event",
    slug: "school-college-event",
    duration: "1200ms",
    title: "School & College Events",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to  VR Event & Entertainment, where we specialize in creating dynamic and memorable school and college events. From spirited pep rallies to sophisticated prom nights, our team is dedicated to bringing your vision to life with creativity and precision. Whether you're planning a graduation ceremony, a cultural festival, or a spirited sports day, we handle every detail—from venue selection to thematic decor and engaging activities—with expertise and enthusiasm. Trust us to deliver an exceptional event that fosters school spirit, celebrates achievements, and creates lasting memories for students, faculty, and guests alike. Elevate your school and college events with us, where every occasion is a success story waiting to be written..
    `,
    additionalImages: [
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-fourteen.png",
      "/assets/events/artist/artsit-eight.png",
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
    ],
    additionalServices: [
      "Complete DJ light and sound setup",
      "Artist management",
      "Theme based decor",
      "Fest organization",
      "Choreography",
      "Photography and videography",
      "All types of tenting setup",
      "Complete Annual function",
      "Sports day drills",
      "Republic day function",
      "Dress",
      "Makeup artist",
      "All types of Choreography",
      "Complete light and sound setup",
      "All types of photography and videography work",
      "Catering service",
      "Volunteer service",
    ],
  },
  {
    id: 7,
    image: "/assets/events/photography.png",
    text: "All type of photography & videography work",
    slug: "all-type-of-photography-videography-work",
    duration: "1400ms",
    title: "All type of photography & videography work",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, where we capture every moment with artistry and precision. Specializing in all types of photography and videography, we are passionate about preserving the essence of your event in stunning visuals. Whether it's a wedding, corporate gathering, or special celebration, our skilled team of photographers and videographers ensure every detail is captured with creativity and professionalism. From candid moments to breath taking portraits, we excel in delivering high-quality images and videos that tell your unique story. Trust us to document your memories with style and grace. Discover the art of visual storytelling with us.
    `,
    additionalImages: [
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
    ],
    additionalServices: [
      "Wedding Ceremony",
      "Haldi Ceremony",
      "Mehndi",
      "Cocktail ceremony",
      "Dj light and sound",
      "Catering",
      "All type artist management",
      "Entertainment",
      "Hospitality",
    ],
  },
  {
    id: 8,
    image: "/assets/events/entertainment.png",
    text: "Entertainment",
    slug: "entertainment",
    duration: "1600ms",
    title: "Entertainment",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, your ultimate source for premier entertainment experiences. Whether you're planning a corporate gala, a wedding reception, or a private party, we specialize in curating unforgettable moments with top-notch entertainment. From live bands to DJs, magicians to dancers, our diverse roster of talented performers ensures we match your event's unique vibe and atmosphere. With meticulous attention to detail and a commitment to excellence, we create seamless entertainment solutions that leave a lasting impression on your guests. Elevate your event with us, where entertainment meets excellence and every celebration shines with brilliance.
    `,
    additionalImages: [
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
      "/assets/images/service-single/2.jpg",
      "/assets/images/service-single/3.jpg",
    ],
    additionalServices: [
      "Wedding Ceremony",
      "Haldi Ceremony",
      "Mehndi",
      "Cocktail ceremony",
      "Dj light and sound",
      "Catering",
      "All type artist management",
      "Entertainment",
      "Hospitality",
    ],
  },
  {
    id: 9,
    image: "/assets/events/celebrity.png",
    text: "Celebrity Artist",
    slug: "celebrity-artist",
    duration: "1600ms",
    title: "Celebrity Artist",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, your gateway to the stars. We specialize in connecting you with celebrity artists who elevate your event to extraordinary heights. Whether you're planning a high-profile corporate function, a dazzling gala, or an exclusive private party, our extensive network includes renowned musicians, actors, comedians, and more. With expertise in negotiating contracts and coordinating logistics, we ensure a seamless experience from start to finish. Trust us to bring star power to your event and create unforgettable moments that leave a lasting impression. Partner with us for a celebrity-driven event that exceeds all expectations.
    `,
    additionalImages: [
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-fourteen.png",
      "/assets/events/artist/artsit-eight.png",
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
    ],
    additionalServices: [
      "Bollywood Film stars",
      "Playback singers",
      "Standup comedian",
      "Punjabi pop singers",
      "Talent hunt singers",
      "Indi pop singers",
      "Sufi singers",
      "Celebrity Emcees",
      "Reality show performance",
      "Live Bands",
      "Models",
      "International performance",
      "Dance troupes",
    ],
  },
  {
    id: 10,
    image: "/assets/events/wedding-services.png",
    text: "Wedding Services",
    slug: "wedding-services",
    duration: "1600ms",
    title: "Wedding Services",
    detailImage: "/assets/images/service-single/1.jpg",
    description: `
      Welcome to VR Event & Entertainment, where we specialize in turning your wedding dreams into cherished memories. With a passion for perfection and an eye for detail, our wedding services are tailored to create elegant and unforgettable celebrations. From intimate ceremonies to lavish receptions, we handle every aspect of your special day with care and expertise. Our dedicated team ensures seamless coordination of venues, decor, catering, and more, allowing you to relax and enjoy every moment. Trust us to make your wedding day as beautiful and magical as you've always imagined. Discover the art of exceptional wedding planning with us.
    `,
    additionalImages: [
      "/assets/events/artist/artsit-sixteen.png",
      "/assets/events/artist/artsit-one.png",
      "/assets/events/artist/artsit-two.png",
      "/assets/events/artist/artsit-three.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-five.png",
      "/assets/events/artist/artsit-six.png",
      "/assets/events/artist/artsit-four.png",
      "/assets/events/artist/artsit-fourteen.png",
    ],
    additionalServices: [
      "Wedding Ceremony",
      "Haldi Ceremony",
      "Mehndi",
      "Cocktail ceremony",
      "Dj light and sound",
      "Catering",
      "All type artist management",
      "Entertainment",
      "Hospitality",
    ],
  },
];
